
INSERT INTO public.agents (slug, name, description, category, icon, credit_cost, active) VALUES
('auditor-prescricao', 'Auditor de Prescrição por Imagem', 'Analise prescrições médicas identificando interações medicamentosas graves, doses incorretas e incompatibilidades. Insira os dados da prescrição e receba um relatório estruturado de segurança com alertas priorizados por gravidade.', 'Prática Clínica e Farmácia', 'ScanEye', 1, true),
('revisor-artigo', 'Revisor de Artigo Científico', 'Analise manuscritos científicos com avaliação IMRAD, score de publicabilidade, checklist metodológico e sugestão de revistas compatíveis. Ideal para pesquisadores que desejam aumentar suas chances de publicação.', 'Pesquisa Acadêmica e Dados', 'FileSearch', 1, true),
('paciente-virtual-voz', 'Simulador de Paciente Virtual', 'Treine habilidades clínicas com pacientes virtuais interativos. O agente interpreta um paciente com sintomas, exames e respostas emocionais realistas, criando cenários imersivos para treinamento de alunos e residentes.', 'EdTech e Professores 4.0', 'UserRound', 1, true),
('gerador-pop-sop', 'Gerador de POP/SOP', 'Gere Procedimentos Operacionais Padrão (POP/SOP) completos seguindo normas ANVISA, ONA e Joint Commission. Documentos estruturados, prontos para impressão e implementação em farmácias e hospitais.', 'Prática Clínica e Farmácia', 'ClipboardList', 1, true),
('farmacovigilancia', 'Monitor de Farmacovigilância', 'Analise eventos adversos, gere relatórios de farmacovigilância e receba alertas sobre notificações de segurança. Ferramenta essencial para profissionais responsáveis pela segurança do paciente.', 'Prática Clínica e Farmácia', 'ShieldAlert', 1, true),
('narrativa-lattes', 'Construtor de Narrativa Lattes', 'Transforme seus dados acadêmicos em narrativas profissionais para editais de fomento, LinkedIn, memoriais descritivos e concursos. Cole seus dados do Lattes e receba textos prontos para uso.', 'Pesquisa Acadêmica e Dados', 'GraduationCap', 1, true),
('comparador-medicamentos', 'Comparador de Medicamentos', 'Compare 2 ou mais medicamentos em eficácia, segurança, custo, disponibilidade no SUS, contraindicações e interações. Ideal para decisões de substituição terapêutica e orientação farmacêutica.', 'Prática Clínica e Farmácia', 'GitCompare', 1, true);
